In [1]:
import joblib
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import set_config
from tempfile import TemporaryDirectory
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import FunctionTransformer
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import StackingClassifier
import xgboost as xgb
from xgboost import XGBClassifier
#from lightgbm import LGBMClassifier
#from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_sample_weight
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn import metrics
import seaborn as sns
import numpy as np
import warnings

In [2]:
target_column = "health_condition"

In [3]:
df = pd.read_csv("data/train.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 690088 entries, 0 to 690087
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       690088 non-null  int64
 1   health_condition         690088 non-null  str
 2   sleep_duration           614089 non-null  float64
 3   heart_rate               682255 non-null  float64
 4   bmi                      676190 non-null  float64
 5   calorie_expenditure      637235 non-null  float64
 6   step_count               676172 non-null  float64
 7   exercise_duration        683187 non-null  float64
 8   water_intake             646611 non-null  float64
 9   diet_type                683187 non-null  str
 10  stress_level             607277 non-null  str
 11  sleep_quality            631757 non-null  str
 12  physical_activity_level  653467 non-null  str
 13  smoking_alcohol          661506 non-null  str
 14  gender                   668715 non-null  str
dtypes: float64(7), int64(1), str(7)
memory usage: 79.0 MB

In [4]:
df['diet_type'] = df['diet_type'].astype('category')
df['stress_level'] = df['stress_level'].replace({'low':0, 'medium':1, 'high':2})
df['sleep_quality'] = df['sleep_quality'].replace({'poor':0, 'average':1, 'good':2})
df['physical_activity_level'] = df['physical_activity_level'].replace({'sedentary':0, 'moderate':1, 'active':2})
df['smoking_alcohol'] = df['smoking_alcohol'].replace({'no':0, 'occasional':1, 'yes':2})
df['gender'] = df['gender'].astype('category')

object_cols = ['stress_level', 'sleep_quality', 'physical_activity_level', 'smoking_alcohol']
for col in object_cols:
    df[col] = df[col].astype('category')
# convert object types to category
# TODO - make this ordered again somehow

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 690088 entries, 0 to 690087
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       690088 non-null  int64
 1   health_condition         690088 non-null  str
 2   sleep_duration           614089 non-null  float64
 3   heart_rate               682255 non-null  float64
 4   bmi                      676190 non-null  float64
 5   calorie_expenditure      637235 non-null  float64
 6   step_count               676172 non-null  float64
 7   exercise_duration        683187 non-null  float64
 8   water_intake             646611 non-null  float64
 9   diet_type                683187 non-null  category
 10  stress_level             607277 non-null  category
 11  sleep_quality            631757 non-null  category
 12  physical_activity_level  653467 non-null  category
 13  smoking_alcohol          661506 non-null  category
 14  gender                   668715 non-null  category
dtypes: category(6), float64(7), int64(1), str(1)
memory usage: 51.3 MB

In [5]:
df['calorie_expenditure_per_step'] = df['calorie_expenditure'] / (df['step_count']+1)
df['step_speed'] = df['step_count'] / (df['exercise_duration']+1)
df['calorie_expenditure_per_min'] = df['calorie_expenditure'] / (df['exercise_duration']+1)
df['calorie_expenditure_per_bmi'] = df['calorie_expenditure'] / (df['bmi']+1)

In [6]:
df.drop('id', axis=1)

,health_condition,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,diet_type,stress_level,sleep_quality,physical_activity_level,smoking_alcohol,gender,calorie_expenditure_per_step,step_speed,calorie_expenditure_per_min,calorie_expenditure_per_bmi
0,unhealthy,5.22,70.6,25.66,2174.0,1326.0,19.8,1.86,veg,2,1,0,2,female,1.638282,63.750000,104.519231,81.545386
1,at-risk,5.53,71.3,25.84,1966.0,9891.0,49.9,1.26,non-veg,0,1,1,2,other,0.198746,194.322200,38.624754,73.248882
2,unhealthy,5.29,75.4,24.54,2688.0,14216.0,38.1,1.60,veg,2,0,2,2,male,0.189069,363.580563,68.746803,105.246672
3,unhealthy,4.70,77.2,23.13,2630.0,7174.0,59.9,2.02,veg,2,1,2,1,female,0.366551,117.799672,43.185550,108.992955
4,at-risk,7.23,73.4,28.44,2560.0,6584.0,46.0,2.25,veg,NaN,1,0,NaN,male,0.388762,140.085106,54.468085,86.956522
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
690083,at-risk,6.31,69.7,24.11,2157.0,NaN,30.8,3.00,non-veg,2,0,2,2,female,NaN,NaN,67.830189,85.902031
690084,at-risk,5.78,54.0,26.36,2858.0,6488.0,52.4,1.46,veg,1,1,1,0,male,0.440438,121.498127,53.520599,104.459064
690085,fit,7.64,85.7,21.91,2195.0,9241.0,41.3,1.57,non-veg,NaN,1,2,0,male,0.237503,218.463357,51.891253,95.809690
690086,at-risk,6.74,73.0,18.73,2061.0,13366.0,56.6,2.60,balanced,NaN,1,2,2,male,0.154186,232.048611,35.781250,104.460213
690087,at-risk,5.55,69.3,24.38,2257.0,5144.0,47.9,1.76,balanced,1,1,1,2,male,0.438678,105.194274,46.155419,88.928290

In [7]:
y = df[target_column].replace({'unhealthy':0, 'at-risk':1, 'fit':2}).astype('int')
X = df.drop(target_column, axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
df_test = pd.read_csv("data/test.csv")

df_submission = pd.read_csv("data/sample_submission.csv")
df_submission.info()

<class 'pandas.DataFrame'>
RangeIndex: 295753 entries, 0 to 295752
Data columns (total 2 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                295753 non-null  int64
 1   health_condition  295753 non-null  str
dtypes: int64(1), str(1)
memory usage: 4.5 MB

In [9]:
df_test['diet_type'] = df_test['diet_type'].astype('category')
df_test['stress_level'] = df_test['stress_level'].replace({'low':0, 'medium':1, 'high':2})
df_test['sleep_quality'] = df_test['sleep_quality'].replace({'poor':0, 'average':1, 'good':2})
df_test['physical_activity_level'] = df_test['physical_activity_level'].replace({'sedentary':0, 'moderate':1, 'active':2})
df_test['smoking_alcohol'] = df_test['smoking_alcohol'].replace({'no':0, 'occasional':1, 'yes':2})
df_test['gender'] = df_test['gender'].astype('category')

object_cols = ['stress_level', 'sleep_quality', 'physical_activity_level', 'smoking_alcohol']
for col in object_cols:
    df_test[col] = df_test[col].astype('category')

df_test['calorie_expenditure_per_step'] = df_test['calorie_expenditure'] / (df_test['step_count']+1)
df_test['step_speed'] = df_test['step_count'] / (df_test['exercise_duration']+1)
df_test['calorie_expenditure_per_min'] = df_test['calorie_expenditure'] / (df_test['exercise_duration']+1)
df_test['calorie_expenditure_per_bmi'] = df_test['calorie_expenditure'] / (df_test['bmi']+1)

In [10]:
train_sample_weight = compute_sample_weight(class_weight="balanced", y=y_train)

model = joblib.load('models/xgboost_tts_80.pkl')
model.fit(X_train, y_train, sample_weight=train_sample_weight, eval_set=[(X_test, y_test)], verbose=0)

XGBClassifier(base_score=None, booster='gbtree', callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=100,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=8,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=100,
              n_jobs=None, num_class=3, ...)

In [11]:
test_sample_weight = compute_sample_weight(class_weight="balanced", y=y_test)
val_score = model.score(X_test, y_test, sample_weight=test_sample_weight)
val_score

0.9504715152293938

In [12]:
X_train.columns
test_features = ['id', 'diet_type', 'calorie_expenditure_per_bmi', 'calorie_expenditure_per_step', 'step_speed', 'calorie_expenditure', 'calorie_expenditure_per_min', 'gender']
rest_of_features = list(set(X_train.columns).difference(set(test_features)))
remove_features = (test_features + rest_of_features)
remove_features.pop()
remove_features

['id',
 'diet_type',
 'calorie_expenditure_per_bmi',
 'calorie_expenditure_per_step',
 'step_speed',
 'calorie_expenditure',
 'calorie_expenditure_per_min',
 'gender',
 'sleep_quality',
 'step_count',
 'heart_rate',
 'physical_activity_level',
 'smoking_alcohol',
 'bmi',
 'water_intake',
 'stress_level',
 'exercise_duration']

In [13]:
val_scores = []

for feature in remove_features:
    X.drop(feature, axis=1, inplace=True)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    model = joblib.load('models/xgboost_tts_80.pkl')
    model.fit(X_train, y_train, sample_weight=train_sample_weight, eval_set=[(X_test, y_test)], verbose=0)

    feature_val_score = model.score(X_test, y_test, sample_weight=test_sample_weight)
    val_scores.append(feature_val_score)

score_df = pd.DataFrame({'Feature': pd.Series(remove_features), 'Validation Score': pd.Series(val_scores)})
score_df

                         Feature  Validation Score
0                             id          0.950384
1                      diet_type          0.950343
2    calorie_expenditure_per_bmi          0.950181
3   calorie_expenditure_per_step          0.950289
4                     step_speed          0.950210
5            calorie_expenditure          0.950452
6    calorie_expenditure_per_min          0.950444
7                         gender          0.950326
8                  sleep_quality          0.949808
9                     step_count          0.949487
10                    heart_rate          0.949465
11       physical_activity_level          0.923932
12               smoking_alcohol          0.923494
13                           bmi          0.916722
14                  water_intake          0.917059
15                  stress_level          0.766574
16             exercise_duration          0.710812